apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      initContainers:
        - name: {{ .Values.initContainer.name }}
          image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Verificando si existe {{ .Values.initContainer.filePath }}..."
              if [ ! -f {{ .Values.initContainer.filePath }} ]; then
                echo "Copiando archivo inicial..."
                cp {{ .Values.initContainer.initFilePath }} {{ .Values.initContainer.filePath }}
                touch {{ .Values.initContainer.initializedFile }}  # Creamos el archivo marcador
              else
                echo "Archivo ya existe. No se copia."
              fi
          volumeMounts:
            - name: food-storage
              mountPath: /data

      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag }}"
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
          env:
            - name: PATH_FILE
              value: {{ .Values.container.env.PATH_FILE }}
          resources:
            requests:
              cpu: {{ .Values.container.resources.requests.cpu }}
              memory: {{ .Values.container.resources.requests.memory }}
            limits:
              cpu: {{ .Values.container.resources.limits.cpu }}
              memory: {{ .Values.container.resources.limits.memory }}
          volumeMounts:
            - name: food-storage
              mountPath: /data

      volumes:
        - name: food-storage
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
