###################################################
# Minikube
###################################################
argo:
  appName: qa-cinema-app  
  repoURL: git@gitlab.com:be-bulder/gitops/minikube/manifest-k8s.git
  targetRevision: qa
  path: helm-charts/cinema-app 
  helm:
    valueFiles:
      - values-qa.yml  
  destinationServer: https://kubernetes.default.svc
  destinationNamespace: qa
  syncPolicy:
    selfHeal: true
    prune: true
    syncOptions:
      createNamespace: true

###################################################
# EKS
###################################################

# argo:
#   environment: qa
#   repoURL: git@gitlab.com:be-bulder/minikube/manifest-eks.git
#   targetRevision: develop
#   destinationServer: https://E3C2D4F5E6D7F8G9H0I1J2K3L4M5N6O7-1234567890.us-west-2.eks.amazonaws.com # actualizar por cluuster ambiente qa
#   destinationNamespace: qa
#   valueFiles:
#     - values-qa.yml
#   syncPolicy:
#     selfHeal: true
#     prune: true
#     syncOptions:
#       CreateNamespace: true
