###################################################
# Minikube
###################################################
argo:
  environment: dev
  repoURL: git@ssh.dev.azure.com:v3/johanmaury/Inicio%20DevOps%20Johan/manifest-k8s
  targetRevision: develop
  destinationServer: https://kubernetes.default.svc
  destinationNamespace: dev
  valueFiles:
    - values-dev.yml
  syncPolicy:
    selfHeal: true
    prune: true
    syncOptions:
      CreateNamespace: true
