apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-cinema-seats 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.argo.repoURL }}
    targetRevision: {{ .Values.argo.targetRevision }}
    path: helm-charts/cinema-seats
    helm:
      valueFiles:
        - values-dev.yml
  destination:
    server: {{ .Values.argo.destinationServer }}
    namespace: {{ .Values.argo.destinationNamespace }}
  syncPolicy:
    automated:
      selfHeal: {{ .Values.argo.syncPolicy.selfHeal }}
      prune: {{ .Values.argo.syncPolicy.prune }}
    syncOptions:
      - CreateNamespace={{ .Values.argo.syncPolicy.syncOptions.CreateNamespace }}
