apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argo.environment }}-cinema-food 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.argo.repoURL }}
    targetRevision: {{ .Values.argo.targetRevision }}
    path: helm-charts/cinema-food 
    helm:
      valueFiles:
        {{- if kindIs "string" .Values.argo.valueFiles }}
        - {{ .Values.argo.valueFiles | quote }}
        {{- else }}
        {{- range .Values.argo.valueFiles }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
  destination:
    server: {{ .Values.argo.destinationServer }}
    namespace: {{ .Values.argo.destinationNamespace }}
  syncPolicy:
    automated:
      selfHeal: {{ .Values.argo.syncPolicy.selfHeal }}
      prune: {{ .Values.argo.syncPolicy.prune }}
    syncOptions:
      - CreateNamespace={{ .Values.argo.syncPolicy.syncOptions.CreateNamespace }}
